#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cp 0.orig 0 -R

runApplication blockMesh

python3 aleatorisch.py

#runApplication setFields

runApplication $(getApplication)

#runApplication decomposePar
#runParallel $(getApplication)

#runApplication reconstructPar

#runApplication postProcess -func sampleDict

#python3 postProc.py

#------------------------------------------------------------------------------
