stages:
  - Build FOAM
  - Build porousMedia
  - Gravity Capillarity

build FOAM:
  stage: Build FOAM
  tags:
    - shell
  before_script:
    - tag_image_fe5=$(sha256sum ci/ubuntu20.04-foam_extend_5.0.dockerfile | grep -Eo '^[a-z0-9]{8}')
  script:
    - |
      if docker image inspect wikkibrasil/ubuntu20.04-foam_extend_5.0:$tag_image_fe5
      then
        echo "FOAM image already exists. Skipping build"
      else
        ci/buildImages.sh --os=ubuntu --os_tag=20.04 --foam_version=foam_extend_5.0 --output_tag=$tag_image_fe5 --images_to_build=1
      fi
  resource_group: demanding
  inherit:
    default:
      - retry

build porousMedia:
  tags:
    - shell
  stage: Build porousMedia
  before_script:
    - tag_image_fe5=$(sha256sum ci/ubuntu20.04-foam_extend_5.0.dockerfile | grep -Eo '^[a-z0-9]{8}')
  script:
    - ci/buildImages.sh --os=ubuntu --os_tag=20.04 --foam_version=foam_extend_5.0 --input_tag=$tag_image_fe5 --output_tag=$CI_COMMIT_SHORT_SHA --images_to_build=2
  resource_group: demanding
  inherit:
    default:
      - retry

Delete Image:
  tags:
    - shell
  stage: .post
  before_script:
  - ''
  script:
    - docker images | awk '/(foam_extend_5.*([3-9] days|weeks)|none)/ {print $3}' | xargs docker rmi -f || true
  when: always

image: wikkibrasil/ubuntu20.04-foam_extend_5.0_porousmedia:$CI_COMMIT_SHORT_SHA

default:
  before_script:
  - source ~/.bashrc_pm
  retry: 1
  artifacts:
    expire_in: "3 days"
    when: always
    paths:
      -  "artifacts/*"

Gravity Capillarity:
  stage: Gravity Capillarity
  script:
    - cd tests/capillarityGravityEquilibrium/
    - ./Allrun
  after_script:
    - mkdir -p $CI_PROJECT_DIR/artifacts/$(basename $PWD) || true
    - cp  tests/capillarityGravityEquilibrium/{log.*,*.png} $CI_PROJECT_DIR/artifacts/$(basename $PWD) || true
  dependencies: []
