#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

phaseSystems/Allwmake $targetType $*
porousModels/Allwmake $targetType $*
blockSystems/Allwmake $targetType $*

speciesCoupledMatrixFoam/Allwmake $targetType $*

#------------------------------------------------------------------------------
